// Generated by scripts/lib/code-synthesizer.mjs

// - - - - - - - - - - - - - - - - - - - -
//            @method {get}
// - - - - - - - - - - - - - - - - - - - -
/*!
 * ESI endpoint: get:/alliances/{alliance_id}/contacts/
 */
/**
 * contact_type string
 */
type GetAlliancesAllianceIdContactsContactType = "character" | "corporation" | "alliance" | "faction";
/**
 * 200 ok array
 *
 * @maxItems 1000
 */
type GetAlliancesAllianceIdContactsOk = GetAlliancesAllianceIdContacts_200Ok[];

/**
 * 200 ok object
 */
interface GetAlliancesAllianceIdContacts_200Ok {
  /**
   * contact_id integer
   */
  contact_id: number;
  contact_type: GetAlliancesAllianceIdContactsContactType;
  /**
   * label_ids array
   *
   * @maxItems 63
   */
  label_ids?: number[];
  /**
   * Standing of the contact
   */
  standing: number;
  [k: string]: unknown | undefined;
}

/*!
 * ESI endpoint: get:/alliances/{alliance_id}/contacts/labels/
 */
/**
 * 200 ok array
 *
 * @maxItems 64
 */
type GetAlliancesAllianceIdContactsLabelsOk = GetAlliancesAllianceIdContactsLabels_200Ok[];

/**
 * 200 ok object
 */
interface GetAlliancesAllianceIdContactsLabels_200Ok {
  /**
   * label_id integer
   */
  label_id: number;
  /**
   * label_name string
   */
  label_name: string;
  [k: string]: unknown | undefined;
}

/*!
 * ESI endpoint: get:/characters/{character_id}/contacts/
 */
/**
 * contact_type string
 */
type GetCharactersCharacterIdContactsContactType = "character" | "corporation" | "alliance" | "faction";
/**
 * 200 ok array
 *
 * @maxItems 1024
 */
type GetCharactersCharacterIdContactsOk = GetCharactersCharacterIdContacts_200Ok[];

/**
 * 200 ok object
 */
interface GetCharactersCharacterIdContacts_200Ok {
  /**
   * contact_id integer
   */
  contact_id: number;
  contact_type: GetCharactersCharacterIdContactsContactType;
  /**
   * Whether this contact is in the blocked list. Note a missing value denotes unknown, not true or false
   */
  is_blocked?: boolean;
  /**
   * Whether this contact is being watched
   */
  is_watched?: boolean;
  /**
   * label_ids array
   *
   * @maxItems 63
   */
  label_ids?: number[];
  /**
   * Standing of the contact
   */
  standing: number;
  [k: string]: unknown | undefined;
}

/*!
 * ESI endpoint: get:/characters/{character_id}/contacts/labels/
 */
/**
 * 200 ok array
 *
 * @maxItems 64
 */
type GetCharactersCharacterIdContactsLabelsOk = GetCharactersCharacterIdContactsLabels_200Ok[];

/**
 * 200 ok object
 */
interface GetCharactersCharacterIdContactsLabels_200Ok {
  /**
   * label_id integer
   */
  label_id: number;
  /**
   * label_name string
   */
  label_name: string;
  [k: string]: unknown | undefined;
}

/*!
 * ESI endpoint: get:/corporations/{corporation_id}/contacts/
 */
/**
 * contact_type string
 */
type GetCorporationsCorporationIdContactsContactType = "character" | "corporation" | "alliance" | "faction";
/**
 * 200 ok array
 *
 * @maxItems 200
 */
type GetCorporationsCorporationIdContactsOk = GetCorporationsCorporationIdContacts_200Ok[];

/**
 * 200 ok object
 */
interface GetCorporationsCorporationIdContacts_200Ok {
  /**
   * contact_id integer
   */
  contact_id: number;
  contact_type: GetCorporationsCorporationIdContactsContactType;
  /**
   * Whether this contact is being watched
   */
  is_watched?: boolean;
  /**
   * label_ids array
   *
   * @maxItems 63
   */
  label_ids?: number[];
  /**
   * Standing of the contact
   */
  standing: number;
  [k: string]: unknown | undefined;
}

/*!
 * ESI endpoint: get:/corporations/{corporation_id}/contacts/labels/
 */
/**
 * 200 ok array
 *
 * @maxItems 64
 */
type GetCorporationsCorporationIdContactsLabelsOk = GetCorporationsCorporationIdContactsLabels_200Ok[];

/**
 * 200 ok object
 */
interface GetCorporationsCorporationIdContactsLabels_200Ok {
  /**
   * label_id integer
   */
  label_id: number;
  /**
   * label_name string
   */
  label_name: string;
  [k: string]: unknown | undefined;
}

// - - - - - - - - - - - - - - - - - - - -
//            @method {post}
// - - - - - - - - - - - - - - - - - - - -
/*!
 * ESI endpoint: post:/characters/{character_id}/contacts/
 */
/**
 * 201 created array
 *
 * @maxItems 100
 */
type PostCharactersCharacterIdContactsCreated = number[];
