// Generated by scripts/lib/code-synthesizer.mjs

// - - - - - - - - - - - - - - - - - - - -
//            @method {get}
// - - - - - - - - - - - - - - - - - - - -
/*!
 * ESI endpoint: get:/corporations/npccorps/
 */
/**
 * 200 ok array
 *
 * @maxItems 500
 */
type GetCorporationsNpccorpsOk = number[];

/*!
 * ESI endpoint: get:/corporations/{corporation_id}/
 */

/**
 * 200 ok object
 */
interface GetCorporationsCorporationIdOk {
  /**
   * ID of the alliance that corporation is a member of, if any
   */
  alliance_id?: number;
  /**
   * ceo_id integer
   */
  ceo_id: number;
  /**
   * creator_id integer
   */
  creator_id: number;
  /**
   * date_founded string
   */
  date_founded?: string;
  /**
   * description string
   */
  description?: string;
  /**
   * faction_id integer
   */
  faction_id?: number;
  /**
   * home_station_id integer
   */
  home_station_id?: number;
  /**
   * member_count integer
   */
  member_count: number;
  /**
   * the full name of the corporation
   */
  name: string;
  /**
   * shares integer
   */
  shares?: number;
  /**
   * tax_rate number
   */
  tax_rate: number;
  /**
   * the short name of the corporation
   */
  ticker: string;
  /**
   * url string
   */
  url?: string;
  /**
   * war_eligible boolean
   */
  war_eligible?: boolean;
  [k: string]: unknown | undefined;
}

/*!
 * ESI endpoint: get:/corporations/{corporation_id}/alliancehistory/
 */
/**
 * 200 ok array
 *
 * @maxItems 10000
 */
type GetCorporationsCorporationIdAlliancehistoryOk = GetCorporationsCorporationIdAlliancehistory_200Ok[];

/**
 * 200 ok object
 */
interface GetCorporationsCorporationIdAlliancehistory_200Ok {
  /**
   * alliance_id integer
   */
  alliance_id?: number;
  /**
   * True if the alliance has been closed
   */
  is_deleted?: boolean;
  /**
   * An incrementing ID that can be used to canonically establish order of records in cases where dates may be ambiguous
   */
  record_id: number;
  /**
   * start_date string
   */
  start_date: string;
  [k: string]: unknown | undefined;
}

/*!
 * ESI endpoint: get:/corporations/{corporation_id}/blueprints/
 */
/**
 * Type of the location_id
 */
type GetCorporationsCorporationIdBlueprintsLocationFlag =
  | "AssetSafety"
  | "AutoFit"
  | "Bonus"
  | "Booster"
  | "BoosterBay"
  | "Capsule"
  | "Cargo"
  | "CorpDeliveries"
  | "CorpSAG1"
  | "CorpSAG2"
  | "CorpSAG3"
  | "CorpSAG4"
  | "CorpSAG5"
  | "CorpSAG6"
  | "CorpSAG7"
  | "CrateLoot"
  | "Deliveries"
  | "DroneBay"
  | "DustBattle"
  | "DustDatabank"
  | "FighterBay"
  | "FighterTube0"
  | "FighterTube1"
  | "FighterTube2"
  | "FighterTube3"
  | "FighterTube4"
  | "FleetHangar"
  | "FrigateEscapeBay"
  | "Hangar"
  | "HangarAll"
  | "HiSlot0"
  | "HiSlot1"
  | "HiSlot2"
  | "HiSlot3"
  | "HiSlot4"
  | "HiSlot5"
  | "HiSlot6"
  | "HiSlot7"
  | "HiddenModifiers"
  | "Implant"
  | "Impounded"
  | "JunkyardReprocessed"
  | "JunkyardTrashed"
  | "LoSlot0"
  | "LoSlot1"
  | "LoSlot2"
  | "LoSlot3"
  | "LoSlot4"
  | "LoSlot5"
  | "LoSlot6"
  | "LoSlot7"
  | "Locked"
  | "MedSlot0"
  | "MedSlot1"
  | "MedSlot2"
  | "MedSlot3"
  | "MedSlot4"
  | "MedSlot5"
  | "MedSlot6"
  | "MedSlot7"
  | "OfficeFolder"
  | "Pilot"
  | "PlanetSurface"
  | "QuafeBay"
  | "QuantumCoreRoom"
  | "Reward"
  | "RigSlot0"
  | "RigSlot1"
  | "RigSlot2"
  | "RigSlot3"
  | "RigSlot4"
  | "RigSlot5"
  | "RigSlot6"
  | "RigSlot7"
  | "SecondaryStorage"
  | "ServiceSlot0"
  | "ServiceSlot1"
  | "ServiceSlot2"
  | "ServiceSlot3"
  | "ServiceSlot4"
  | "ServiceSlot5"
  | "ServiceSlot6"
  | "ServiceSlot7"
  | "ShipHangar"
  | "ShipOffline"
  | "Skill"
  | "SkillInTraining"
  | "SpecializedAmmoHold"
  | "SpecializedCommandCenterHold"
  | "SpecializedFuelBay"
  | "SpecializedGasHold"
  | "SpecializedIndustrialShipHold"
  | "SpecializedLargeShipHold"
  | "SpecializedMaterialBay"
  | "SpecializedMediumShipHold"
  | "SpecializedMineralHold"
  | "SpecializedOreHold"
  | "SpecializedPlanetaryCommoditiesHold"
  | "SpecializedSalvageHold"
  | "SpecializedShipHold"
  | "SpecializedSmallShipHold"
  | "StructureActive"
  | "StructureFuel"
  | "StructureInactive"
  | "StructureOffline"
  | "SubSystemBay"
  | "SubSystemSlot0"
  | "SubSystemSlot1"
  | "SubSystemSlot2"
  | "SubSystemSlot3"
  | "SubSystemSlot4"
  | "SubSystemSlot5"
  | "SubSystemSlot6"
  | "SubSystemSlot7"
  | "Unlocked"
  | "Wallet"
  | "Wardrobe";
/**
 * 200 ok array
 *
 * @maxItems 1000
 */
type GetCorporationsCorporationIdBlueprintsOk = GetCorporationsCorporationIdBlueprints_200Ok[];

/**
 * 200 ok object
 */
interface GetCorporationsCorporationIdBlueprints_200Ok {
  /**
   * Unique ID for this item.
   */
  item_id: number;
  location_flag: GetCorporationsCorporationIdBlueprintsLocationFlag;
  /**
   * References a station, a ship or an item_id if this blueprint is located within a container.
   */
  location_id: number;
  /**
   * Material Efficiency Level of the blueprint.
   */
  material_efficiency: number;
  /**
   * A range of numbers with a minimum of -2 and no maximum value where -1 is an original and -2 is a copy. It can be a positive integer if it is a stack of blueprint originals fresh from the market (e.g. no activities performed on them yet).
   */
  quantity: number;
  /**
   * Number of runs remaining if the blueprint is a copy, -1 if it is an original.
   */
  runs: number;
  /**
   * Time Efficiency Level of the blueprint.
   */
  time_efficiency: number;
  type_id: number;
  [k: string]: unknown | undefined;
}

/*!
 * ESI endpoint: get:/corporations/{corporation_id}/containers/logs/
 */
/**
 * action string
 */
type GetCorporationsCorporationIdContainersLogsAction =
  | "add"
  | "assemble"
  | "configure"
  | "enter_password"
  | "lock"
  | "move"
  | "repackage"
  | "set_name"
  | "set_password"
  | "unlock";
/**
 * location_flag string
 */
type GetCorporationsCorporationIdContainersLogsLocationFlag =
  | "AssetSafety"
  | "AutoFit"
  | "Bonus"
  | "Booster"
  | "BoosterBay"
  | "Capsule"
  | "Cargo"
  | "CorpDeliveries"
  | "CorpSAG1"
  | "CorpSAG2"
  | "CorpSAG3"
  | "CorpSAG4"
  | "CorpSAG5"
  | "CorpSAG6"
  | "CorpSAG7"
  | "CrateLoot"
  | "Deliveries"
  | "DroneBay"
  | "DustBattle"
  | "DustDatabank"
  | "FighterBay"
  | "FighterTube0"
  | "FighterTube1"
  | "FighterTube2"
  | "FighterTube3"
  | "FighterTube4"
  | "FleetHangar"
  | "FrigateEscapeBay"
  | "Hangar"
  | "HangarAll"
  | "HiSlot0"
  | "HiSlot1"
  | "HiSlot2"
  | "HiSlot3"
  | "HiSlot4"
  | "HiSlot5"
  | "HiSlot6"
  | "HiSlot7"
  | "HiddenModifiers"
  | "Implant"
  | "Impounded"
  | "JunkyardReprocessed"
  | "JunkyardTrashed"
  | "LoSlot0"
  | "LoSlot1"
  | "LoSlot2"
  | "LoSlot3"
  | "LoSlot4"
  | "LoSlot5"
  | "LoSlot6"
  | "LoSlot7"
  | "Locked"
  | "MedSlot0"
  | "MedSlot1"
  | "MedSlot2"
  | "MedSlot3"
  | "MedSlot4"
  | "MedSlot5"
  | "MedSlot6"
  | "MedSlot7"
  | "OfficeFolder"
  | "Pilot"
  | "PlanetSurface"
  | "QuafeBay"
  | "QuantumCoreRoom"
  | "Reward"
  | "RigSlot0"
  | "RigSlot1"
  | "RigSlot2"
  | "RigSlot3"
  | "RigSlot4"
  | "RigSlot5"
  | "RigSlot6"
  | "RigSlot7"
  | "SecondaryStorage"
  | "ServiceSlot0"
  | "ServiceSlot1"
  | "ServiceSlot2"
  | "ServiceSlot3"
  | "ServiceSlot4"
  | "ServiceSlot5"
  | "ServiceSlot6"
  | "ServiceSlot7"
  | "ShipHangar"
  | "ShipOffline"
  | "Skill"
  | "SkillInTraining"
  | "SpecializedAmmoHold"
  | "SpecializedCommandCenterHold"
  | "SpecializedFuelBay"
  | "SpecializedGasHold"
  | "SpecializedIndustrialShipHold"
  | "SpecializedLargeShipHold"
  | "SpecializedMaterialBay"
  | "SpecializedMediumShipHold"
  | "SpecializedMineralHold"
  | "SpecializedOreHold"
  | "SpecializedPlanetaryCommoditiesHold"
  | "SpecializedSalvageHold"
  | "SpecializedShipHold"
  | "SpecializedSmallShipHold"
  | "StructureActive"
  | "StructureFuel"
  | "StructureInactive"
  | "StructureOffline"
  | "SubSystemBay"
  | "SubSystemSlot0"
  | "SubSystemSlot1"
  | "SubSystemSlot2"
  | "SubSystemSlot3"
  | "SubSystemSlot4"
  | "SubSystemSlot5"
  | "SubSystemSlot6"
  | "SubSystemSlot7"
  | "Unlocked"
  | "Wallet"
  | "Wardrobe";
/**
 * Type of password set if action is of type SetPassword or EnterPassword
 */
type GetCorporationsCorporationIdContainersLogsPasswordType = "config" | "general";
/**
 * 200 ok array
 *
 * @maxItems 1000
 */
type GetCorporationsCorporationIdContainersLogsOk = GetCorporationsCorporationIdContainersLogs_200Ok[];

/**
 * 200 ok object
 */
interface GetCorporationsCorporationIdContainersLogs_200Ok {
  action: GetCorporationsCorporationIdContainersLogsAction;
  /**
   * ID of the character who performed the action.
   */
  character_id: number;
  /**
   * ID of the container
   */
  container_id: number;
  container_type_id: number;
  location_flag: GetCorporationsCorporationIdContainersLogsLocationFlag;
  /**
   * location_id integer
   */
  location_id: number;
  /**
   * Timestamp when this log was created
   */
  logged_at: string;
  /**
   * new_config_bitmask integer
   */
  new_config_bitmask?: number;
  /**
   * old_config_bitmask integer
   */
  old_config_bitmask?: number;
  password_type?: GetCorporationsCorporationIdContainersLogsPasswordType;
  /**
   * Quantity of the item being acted upon
   */
  quantity?: number;
  type_id?: number;
  [k: string]: unknown | undefined;
}

/*!
 * ESI endpoint: get:/corporations/{corporation_id}/divisions/
 */
/**
 * hangar array
 *
 * @maxItems 7
 */
type GetCorporationsCorporationIdDivisionsHangar = GetCorporationsCorporationIdDivisionsHangarHangar[];
/**
 * wallet array
 *
 * @maxItems 7
 */
type GetCorporationsCorporationIdDivisionsWallet = GetCorporationsCorporationIdDivisionsWalletWallet[];

/**
 * 200 ok object
 */
interface GetCorporationsCorporationIdDivisionsOk {
  hangar?: GetCorporationsCorporationIdDivisionsHangar;
  wallet?: GetCorporationsCorporationIdDivisionsWallet;
  [k: string]: unknown | undefined;
}
/**
 * hangar object
 */
interface GetCorporationsCorporationIdDivisionsHangarHangar {
  /**
   * division integer
   */
  division?: number;
  /**
   * name string
   */
  name?: string;
  [k: string]: unknown | undefined;
}
/**
 * wallet object
 */
interface GetCorporationsCorporationIdDivisionsWalletWallet {
  /**
   * division integer
   */
  division?: number;
  /**
   * name string
   */
  name?: string;
  [k: string]: unknown | undefined;
}

/*!
 * ESI endpoint: get:/corporations/{corporation_id}/facilities/
 */
/**
 * 200 ok array
 *
 * @maxItems 1000
 */
type GetCorporationsCorporationIdFacilitiesOk = GetCorporationsCorporationIdFacilities_200Ok[];

/**
 * 200 ok object
 */
interface GetCorporationsCorporationIdFacilities_200Ok {
  /**
   * facility_id integer
   */
  facility_id: number;
  /**
   * system_id integer
   */
  system_id: number;
  type_id: number;
  [k: string]: unknown | undefined;
}

/*!
 * ESI endpoint: get:/corporations/{corporation_id}/icons/
 */

/**
 * 200 ok object
 */
interface GetCorporationsCorporationIdIconsOk {
  /**
   * px128x128 string
   */
  px128x128?: string;
  /**
   * px256x256 string
   */
  px256x256?: string;
  /**
   * px64x64 string
   */
  px64x64?: string;
  [k: string]: unknown | undefined;
}

/*!
 * ESI endpoint: get:/corporations/{corporation_id}/medals/
 */
/**
 * 200 ok array
 *
 * @maxItems 1000
 */
type GetCorporationsCorporationIdMedalsOk = GetCorporationsCorporationIdMedals_200Ok[];

/**
 * 200 ok object
 */
interface GetCorporationsCorporationIdMedals_200Ok {
  /**
   * created_at string
   */
  created_at: string;
  /**
   * ID of the character who created this medal
   */
  creator_id: number;
  /**
   * description string
   */
  description: string;
  /**
   * medal_id integer
   */
  medal_id: number;
  /**
   * title string
   */
  title: string;
  [k: string]: unknown | undefined;
}

/*!
 * ESI endpoint: get:/corporations/{corporation_id}/medals/issued/
 */
/**
 * status string
 */
type GetCorporationsCorporationIdMedalsIssuedStatus = "private" | "public";
/**
 * 200 ok array
 *
 * @maxItems 1000
 */
type GetCorporationsCorporationIdMedalsIssuedOk = GetCorporationsCorporationIdMedalsIssued_200Ok[];

/**
 * 200 ok object
 */
interface GetCorporationsCorporationIdMedalsIssued_200Ok {
  /**
   * ID of the character who was rewarded this medal
   */
  character_id: number;
  /**
   * issued_at string
   */
  issued_at: string;
  /**
   * ID of the character who issued the medal
   */
  issuer_id: number;
  /**
   * medal_id integer
   */
  medal_id: number;
  /**
   * reason string
   */
  reason: string;
  status: GetCorporationsCorporationIdMedalsIssuedStatus;
  [k: string]: unknown | undefined;
}

/*!
 * ESI endpoint: get:/corporations/{corporation_id}/members/
 */
/**
 * A list of character IDs
 *
 * @maxItems 12601
 */
type GetCorporationsCorporationIdMembersOk = number[];

/*!
 * ESI endpoint: get:/corporations/{corporation_id}/members/limit/
 */
/**
 * 200 ok integer
 */
type GetCorporationsCorporationIdMembersLimitOk = number;

/*!
 * ESI endpoint: get:/corporations/{corporation_id}/members/titles/
 */
/**
 * 200 ok array
 *
 * @maxItems 12601
 */
type GetCorporationsCorporationIdMembersTitlesOk = GetCorporationsCorporationIdMembersTitles_200Ok[];

/**
 * 200 ok object
 */
interface GetCorporationsCorporationIdMembersTitles_200Ok {
  /**
   * character_id integer
   */
  character_id: number;
  /**
   * A list of title_id
   *
   * @maxItems 16
   */
  titles: number[];
  [k: string]: unknown | undefined;
}

/*!
 * ESI endpoint: get:/corporations/{corporation_id}/membertracking/
 */
/**
 * 200 ok array
 *
 * @maxItems 12601
 */
type GetCorporationsCorporationIdMembertrackingOk = GetCorporationsCorporationIdMembertracking_200Ok[];

/**
 * 200 ok object
 */
interface GetCorporationsCorporationIdMembertracking_200Ok {
  /**
   * base_id integer
   */
  base_id?: number;
  /**
   * character_id integer
   */
  character_id: number;
  /**
   * location_id integer
   */
  location_id?: number;
  /**
   * logoff_date string
   */
  logoff_date?: string;
  /**
   * logon_date string
   */
  logon_date?: string;
  ship_type_id?: number;
  /**
   * start_date string
   */
  start_date?: string;
  [k: string]: unknown | undefined;
}

/*!
 * ESI endpoint: get:/corporations/{corporation_id}/roles/
 */

/**
 * grantable_role string
 */
type GetCorporationsCorporationIdRolesGrantableRole = __CorporationRole;

/**
 * grantable_roles array
 *
 * @maxItems 100
 */
type GetCorporationsCorporationIdRolesGrantableRoles = __CorporationRole[];

/**
 * grantable_roles_at_base string
 */
type GetCorporationsCorporationIdRolesGrantableRolesAtBaseGrantableRolesAtBase = __CorporationRole;

/**
 * grantable_roles_at_base array
 *
 * @maxItems 100
 */
type GetCorporationsCorporationIdRolesGrantableRolesAtBase = __CorporationRole[];

/**
 * grantable_roles_at_hq string
 */
type GetCorporationsCorporationIdRolesGrantableRolesAtHqGrantableRolesAtHq = __CorporationRole;

/**
 * grantable_roles_at_hq array
 *
 * @maxItems 100
 */
type GetCorporationsCorporationIdRolesGrantableRolesAtHq = __CorporationRole[];

/**
 * grantable_roles_at_other string
 */
type GetCorporationsCorporationIdRolesGrantableRolesAtOtherGrantableRolesAtOther = __CorporationRole;

/**
 * grantable_roles_at_other array
 *
 * @maxItems 100
 */
type GetCorporationsCorporationIdRolesGrantableRolesAtOther = __CorporationRole[];

/**
 * role string
 */
type GetCorporationsCorporationIdRolesRole = __CorporationRole;

/**
 * roles array
 *
 * @maxItems 100
 */
type GetCorporationsCorporationIdRolesRoles = __CorporationRole[];

/**
 * roles_at_base string
 */
type GetCorporationsCorporationIdRolesRolesAtBaseRolesAtBase = __CorporationRole;

/**
 * roles_at_base array
 *
 * @maxItems 100
 */
type GetCorporationsCorporationIdRolesRolesAtBase = __CorporationRole[];

/**
 * roles_at_hq string
 */
type GetCorporationsCorporationIdRolesRolesAtHqRolesAtHq = __CorporationRole;

/**
 * roles_at_hq array
 *
 * @maxItems 100
 */
type GetCorporationsCorporationIdRolesRolesAtHq = __CorporationRole[];

/**
 * roles_at_other string
 */
type GetCorporationsCorporationIdRolesRolesAtOtherRolesAtOther = __CorporationRole;

/**
 * roles_at_other array
 *
 * @maxItems 100
 */
type GetCorporationsCorporationIdRolesRolesAtOther = __CorporationRole[];

/**
 * 200 ok array
 *
 * @maxItems 12601
 */
type GetCorporationsCorporationIdRolesOk = GetCorporationsCorporationIdRoles_200Ok[];

/**
 * 200 ok object
 */
interface GetCorporationsCorporationIdRoles_200Ok {
  /**
   * character_id integer
   */
  character_id: number;
  grantable_roles?: GetCorporationsCorporationIdRolesGrantableRoles;
  grantable_roles_at_base?: GetCorporationsCorporationIdRolesGrantableRolesAtBase;
  grantable_roles_at_hq?: GetCorporationsCorporationIdRolesGrantableRolesAtHq;
  grantable_roles_at_other?: GetCorporationsCorporationIdRolesGrantableRolesAtOther;
  roles?: GetCorporationsCorporationIdRolesRoles;
  roles_at_base?: GetCorporationsCorporationIdRolesRolesAtBase;
  roles_at_hq?: GetCorporationsCorporationIdRolesRolesAtHq;
  roles_at_other?: GetCorporationsCorporationIdRolesRolesAtOther;
  [k: string]: unknown | undefined;
}

/*!
 * ESI endpoint: get:/corporations/{corporation_id}/roles/history/
 */

/**
 * Corporation role string
 * grantable_role string
 */
type __CorporationRole = __CharacterRole;

/**
 * new_role string
 */
type GetCorporationsCorporationIdRolesHistoryNewRole = __CorporationRole;

/**
 * new_roles array
 *
 * @maxItems 50
 */
type GetCorporationsCorporationIdRolesHistoryNewRoles = __CorporationRole[];

/**
 * old_role string
 */
type GetCorporationsCorporationIdRolesHistoryOldRole = __CorporationRole;

/**
 * old_roles array
 *
 * @maxItems 50
 */
type GetCorporationsCorporationIdRolesHistoryOldRoles = __CorporationRole[];

/**
 * role_type string
 */
type GetCorporationsCorporationIdRolesHistoryRoleType =
  | "grantable_roles"
  | "grantable_roles_at_base"
  | "grantable_roles_at_hq"
  | "grantable_roles_at_other"
  | "roles"
  | "roles_at_base"
  | "roles_at_hq"
  | "roles_at_other";

/**
 * 200 ok array
 *
 * @maxItems 1000
 */
type GetCorporationsCorporationIdRolesHistoryOk = GetCorporationsCorporationIdRolesHistory_200Ok[];

/**
 * 200 ok object
 */
interface GetCorporationsCorporationIdRolesHistory_200Ok {
  /**
   * changed_at string
   */
  changed_at: string;
  /**
   * The character whose roles are changed
   */
  character_id: number;
  /**
   * ID of the character who issued this change
   */
  issuer_id: number;
  new_roles: GetCorporationsCorporationIdRolesHistoryNewRoles;
  old_roles: GetCorporationsCorporationIdRolesHistoryOldRoles;
  role_type: GetCorporationsCorporationIdRolesHistoryRoleType;
  [k: string]: unknown | undefined;
}

/*!
 * ESI endpoint: get:/corporations/{corporation_id}/shareholders/
 */
/**
 * shareholder_type string
 */
type GetCorporationsCorporationIdShareholdersShareholderType = "character" | "corporation";
/**
 * List of shareholders
 *
 * @maxItems 1000
 */
type GetCorporationsCorporationIdShareholdersOk = GetCorporationsCorporationIdShareholders_200Ok[];

/**
 * 200 ok object
 */
interface GetCorporationsCorporationIdShareholders_200Ok {
  /**
   * share_count integer
   */
  share_count: number;
  /**
   * shareholder_id integer
   */
  shareholder_id: number;
  shareholder_type: GetCorporationsCorporationIdShareholdersShareholderType;
  [k: string]: unknown | undefined;
}

/*!
 * ESI endpoint: get:/corporations/{corporation_id}/standings/
 */
/**
 * from_type string
 */
type GetCorporationsCorporationIdStandingsFromType = "agent" | "npc_corp" | "faction";
/**
 * 200 ok array
 *
 * @maxItems 1000
 */
type GetCorporationsCorporationIdStandingsOk = GetCorporationsCorporationIdStandings_200Ok[];

/**
 * 200 ok object
 */
interface GetCorporationsCorporationIdStandings_200Ok {
  /**
   * from_id integer
   */
  from_id: number;
  from_type: GetCorporationsCorporationIdStandingsFromType;
  /**
   * standing number
   */
  standing: number;
  [k: string]: unknown | undefined;
}

/*!
 * ESI endpoint: get:/corporations/{corporation_id}/starbases/
 */
/**
 * state string
 */
type GetCorporationsCorporationIdStarbasesState =
  | "offline"
  | "online"
  | "onlining"
  | "reinforced"
  | "unanchoring";
/**
 * 200 ok array
 *
 * @maxItems 1000
 */
type GetCorporationsCorporationIdStarbasesOk = GetCorporationsCorporationIdStarbases_200Ok[];

/**
 * 200 ok object
 */
interface GetCorporationsCorporationIdStarbases_200Ok {
  /**
   * The moon this starbase (POS) is anchored on, unanchored POSes do not have this information
   */
  moon_id?: number;
  /**
   * When the POS onlined, for starbases (POSes) in online state
   */
  onlined_since?: string;
  /**
   * When the POS will be out of reinforcement, for starbases (POSes) in reinforced state
   */
  reinforced_until?: string;
  /**
   * Unique ID for this starbase (POS)
   */
  starbase_id: number;
  state?: GetCorporationsCorporationIdStarbasesState;
  /**
   * The solar system this starbase (POS) is in, unanchored POSes have this information
   */
  system_id: number;
  type_id: number;
  /**
   * When the POS started unanchoring, for starbases (POSes) in unanchoring state
   */
  unanchor_at?: string;
  [k: string]: unknown | undefined;
}

/*!
 * ESI endpoint: get:/corporations/{corporation_id}/starbases/{starbase_id}/
 */

/**
 * Who can perform actions related to starbase (POS) or its structures.
 *
 * This type defines the potential access levels for various operations such as anchoring,
 * taking fuel, viewing fuel bay, onlining, offlining, and unanchoring starbase (POS).
 */
type __StarbaseAccessLevel =
  | "alliance_member"
  | "config_starbase_equipment_role"
  | "corporation_member"
  | "starbase_fuel_technician_role";

/**
 * Fuel blocks and other things that will be consumed when operating a starbase (POS)
 *
 * @maxItems 20
 */
type StarbaseFuels = GetCorporationsCorporationIdStarbasesStarbaseIdFuel[];

/**
 * fuel object
 */
interface GetCorporationsCorporationIdStarbasesStarbaseIdFuel {
  /**
   * quantity integer
   */
  quantity: number;
  /**
   * type_id integer
   */
  type_id: number;
  /**
   * Additional unspecified fields
   */
  [k: string]: unknown | undefined;
}

/**
 * 200 ok object
 */
interface GetCorporationsCorporationIdStarbasesStarbaseIdOk {
  /**
   * allow_alliance_members boolean
   */
  allow_alliance_members: boolean;

  /**
   * allow_corporation_members boolean
   */
  allow_corporation_members: boolean;

  /**
   * Who can anchor starbase (POS) and its structures
   */
  anchor: __StarbaseAccessLevel;

  /**
   * attack_if_at_war boolean
   */
  attack_if_at_war: boolean;

  /**
   * attack_if_other_security_status_dropping boolean
   */
  attack_if_other_security_status_dropping: boolean;

  /**
   * Starbase (POS) will attack if target's security standing is lower than this value
   */
  attack_security_status_threshold?: number;

  /**
   * Starbase (POS) will attack if target's standing is lower than this value
   */
  attack_standing_threshold?: number;

  /**
   * Who can take fuel blocks out of the starbase (POS)'s fuel bay
   */
  fuel_bay_take: __StarbaseAccessLevel;

  /**
   * Who can view the starbase (POS)'s fuel bay. Characters either need to have required role or belong to the starbase (POS) owner's corporation or alliance, as described by the enum, all other access settings follow the same scheme
   */
  fuel_bay_view: __StarbaseAccessLevel;

  /**
   * Fuel blocks and other things that will be consumed when operating a starbase (POS)
   */
  fuels?: StarbaseFuels;

  /**
   * Who can offline starbase (POS) and its structures
   */
  offline: __StarbaseAccessLevel;

  /**
   * Who can online starbase (POS) and its structures
   */
  online: __StarbaseAccessLevel;

  /**
   * Who can unanchor starbase (POS) and its structures
   */
  unanchor: __StarbaseAccessLevel;

  /**
   * True if the starbase (POS) is using alliance standings, otherwise using corporation's
   */
  use_alliance_standings: boolean;

  /**
   * Additional unspecified fields
   */
  [k: string]: unknown | undefined;
}

/*!
 * ESI endpoint: get:/corporations/{corporation_id}/structures/
 */
/**
 * state string
 */
type GetCorporationsCorporationIdStructuresServiceState = "online" | "offline" | "cleanup";
/**
 * Contains a list of service upgrades, and their state
 *
 * @maxItems 10
 */
type GetCorporationsCorporationIdStructuresServices = GetCorporationsCorporationIdStructuresService[];
/**
 * state string
 */
type GetCorporationsCorporationIdStructuresState =
  | "anchor_vulnerable"
  | "anchoring"
  | "armor_reinforce"
  | "armor_vulnerable"
  | "deploy_vulnerable"
  | "fitting_invulnerable"
  | "hull_reinforce"
  | "hull_vulnerable"
  | "online_deprecated"
  | "onlining_vulnerable"
  | "shield_vulnerable"
  | "unanchored"
  | "unknown";
/**
 * 200 ok array
 *
 * @maxItems 250
 */
type GetCorporationsCorporationIdStructuresOk = GetCorporationsCorporationIdStructures_200Ok[];

/**
 * 200 ok object
 */
interface GetCorporationsCorporationIdStructures_200Ok {
  /**
   * ID of the corporation that owns the structure
   */
  corporation_id: number;
  /**
   * Date on which the structure will run out of fuel
   */
  fuel_expires?: string;
  /**
   * The structure name
   */
  name?: string;
  /**
   * The date and time when the structure's newly requested reinforcement times (e.g. next_reinforce_hour and next_reinforce_day) will take effect
   */
  next_reinforce_apply?: string;
  /**
   * The requested change to reinforce_hour that will take effect at the time shown by next_reinforce_apply
   */
  next_reinforce_hour?: number;
  /**
   * The id of the ACL profile for this citadel
   */
  profile_id: number;
  /**
   * The hour of day that determines the four hour window when the structure will randomly exit its reinforcement periods and become vulnerable to attack against its armor and/or hull. The structure will become vulnerable at a random time that is +/- 2 hours centered on the value of this property
   */
  reinforce_hour?: number;
  services?: GetCorporationsCorporationIdStructuresServices;
  state: GetCorporationsCorporationIdStructuresState;
  /**
   * Date at which the structure will move to it's next state
   */
  state_timer_end?: string;
  /**
   * Date at which the structure entered it's current state
   */
  state_timer_start?: string;
  /**
   * The Item ID of the structure
   */
  structure_id: number;
  /**
   * The solar system the structure is in
   */
  system_id: number;
  type_id: number;
  /**
   * Date at which the structure will unanchor
   */
  unanchors_at?: string;
  [k: string]: unknown | undefined;
}
/**
 * service object
 */
interface GetCorporationsCorporationIdStructuresService {
  /**
   * name string
   */
  name: string;
  state: GetCorporationsCorporationIdStructuresServiceState;
  [k: string]: unknown | undefined;
}

/*!
 * ESI endpoint: get:/corporations/{corporation_id}/titles/
 */

/**
 * Base role string for all roles and grantable roles.
 */
type GccIdTitlesBaseRole =
  | "Account_Take_1"
  | "Account_Take_2"
  | "Account_Take_3"
  | "Account_Take_4"
  | "Account_Take_5"
  | "Account_Take_6"
  | "Account_Take_7"
  | "Accountant"
  | "Auditor"
  | "Brand_Manager"
  | "Communications_Officer"
  | "Config_Equipment"
  | "Config_Starbase_Equipment"
  | "Container_Take_1"
  | "Container_Take_2"
  | "Container_Take_3"
  | "Container_Take_4"
  | "Container_Take_5"
  | "Container_Take_6"
  | "Container_Take_7"
  | "Contract_Manager"
  | "Deliveries_Container_Take"
  | "Deliveries_Query"
  | "Deliveries_Take"
  | "Diplomat"
  | "Director"
  | "Factory_Manager"
  | "Fitting_Manager"
  | "Hangar_Query_1"
  | "Hangar_Query_2"
  | "Hangar_Query_3"
  | "Hangar_Query_4"
  | "Hangar_Query_5"
  | "Hangar_Query_6"
  | "Hangar_Query_7"
  | "Hangar_Take_1"
  | "Hangar_Take_2"
  | "Hangar_Take_3"
  | "Hangar_Take_4"
  | "Hangar_Take_5"
  | "Hangar_Take_6"
  | "Hangar_Take_7"
  | "Junior_Accountant"
  | "Personnel_Manager"
  | "Project_Manager"
  | "Rent_Factory_Facility"
  | "Rent_Office"
  | "Rent_Research_Facility"
  | "Security_Officer"
  | "Skill_Plan_Manager"
  | "Starbase_Defense_Operator"
  | "Starbase_Fuel_Technician"
  | "Station_Manager"
  | "Trader";

/**
 * grantable_role string
 */
type GetCorporationsCorporationIdTitlesGrantableRole = GccIdTitlesBaseRole;

/**
 * grantable_roles array
 *
 * @maxItems 50
 */
type GetCorporationsCorporationIdTitlesGrantableRoles = GccIdTitlesBaseRole[];

/**
 * grantable_roles_at_base string
 */
type GetCorporationsCorporationIdTitlesGrantableRolesAtBaseGrantableRolesAtBase = GccIdTitlesBaseRole;

/**
 * grantable_roles_at_base array
 *
 * @maxItems 50
 */
type GetCorporationsCorporationIdTitlesGrantableRolesAtBase = GccIdTitlesBaseRole[];

/**
 * grantable_roles_at_hq string
 */
type GetCorporationsCorporationIdTitlesGrantableRolesAtHqGrantableRolesAtHq = GccIdTitlesBaseRole;

/**
 * grantable_roles_at_hq array
 *
 * @maxItems 50
 */
type GetCorporationsCorporationIdTitlesGrantableRolesAtHq = GccIdTitlesBaseRole[];

/**
 * grantable_roles_at_other string
 */
type GetCorporationsCorporationIdTitlesGrantableRolesAtOtherGrantableRolesAtOther = GccIdTitlesBaseRole;

/**
 * grantable_roles_at_other array
 *
 * @maxItems 50
 */
type GetCorporationsCorporationIdTitlesGrantableRolesAtOther = GccIdTitlesBaseRole[];

/**
 * role string
 */
type GetCorporationsCorporationIdTitlesRole = GccIdTitlesBaseRole;

/**
 * roles array
 *
 * @maxItems 50
 */
type GetCorporationsCorporationIdTitlesRoles = GccIdTitlesBaseRole[];

/**
 * roles_at_base string
 */
type GetCorporationsCorporationIdTitlesRolesAtBaseRolesAtBase = GccIdTitlesBaseRole;

/**
 * roles_at_base array
 *
 * @maxItems 50
 */
type GetCorporationsCorporationIdTitlesRolesAtBase = GccIdTitlesBaseRole[];

/**
 * roles_at_hq string
 */
type GetCorporationsCorporationIdTitlesRolesAtHqRolesAtHq = GccIdTitlesBaseRole;

/**
 * roles_at_hq array
 *
 * @maxItems 50
 */
type GetCorporationsCorporationIdTitlesRolesAtHq = GccIdTitlesBaseRole[];

/**
 * roles_at_other string
 */
type GetCorporationsCorporationIdTitlesRolesAtOtherRolesAtOther = GccIdTitlesBaseRole;

/**
 * roles_at_other array
 *
 * @maxItems 50
 */
type GetCorporationsCorporationIdTitlesRolesAtOther = GccIdTitlesBaseRole[];

/**
 * 200 ok array
 *
 * @maxItems 16
 */
type GetCorporationsCorporationIdTitlesOk = GetCorporationsCorporationIdTitles_200Ok[];

/**
 * 200 ok object
 */
interface GetCorporationsCorporationIdTitles_200Ok {
  grantable_roles?: GetCorporationsCorporationIdTitlesGrantableRoles;
  grantable_roles_at_base?: GetCorporationsCorporationIdTitlesGrantableRolesAtBase;
  grantable_roles_at_hq?: GetCorporationsCorporationIdTitlesGrantableRolesAtHq;
  grantable_roles_at_other?: GetCorporationsCorporationIdTitlesGrantableRolesAtOther;
  /**
   * name string
   */
  name?: string;
  roles?: GetCorporationsCorporationIdTitlesRoles;
  roles_at_base?: GetCorporationsCorporationIdTitlesRolesAtBase;
  roles_at_hq?: GetCorporationsCorporationIdTitlesRolesAtHq;
  roles_at_other?: GetCorporationsCorporationIdTitlesRolesAtOther;
  /**
   * title_id integer
   */
  title_id?: number;
  [k: string]: unknown | undefined;
}
