// Generated by scripts/lib/code-synthesizer.mjs

// - - - - - - - - - - - - - - - - - - - -
//            @method {get}
// - - - - - - - - - - - - - - - - - - - -
/*!
 * ESI endpoint: get:/route/{origin}/{destination}/
 */
/**
 * Solar systems in route
 *
 * @maxItems 1000
 */
type GetRouteOriginDestinationOk = number[];
